<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-J1BNB1Q" failures="1" tests="2" name="com.Vtiger_Application.TC003_ContactWithOrgTest" time="170.371" errors="0" timestamp="2022-07-19T15:22:40 IST" skipped="0">
  <testcase classname="com.Vtiger_Application.TC003_ContactWithOrgTest" name="contactWithOrgTest" time="133.377">
    <failure message="expected [Dietrich] but found [Yesu]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Dietrich] but found [Yesu]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.Vtiger_Application.TC003_ContactWithOrgTest.contactWithOrgTest(TC003_ContactWithOrgTest.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
    </failure>
  </testcase> <!-- contactWithOrgTest -->
  <system-out/>
  <testcase classname="com.Vtiger_Application.TC003_ContactWithOrgTest" name="createContactTest" time="36.994"/>
  <system-out/>
</testsuite> <!-- com.Vtiger_Application.TC003_ContactWithOrgTest -->
